# Required-Validierung (pflichtfelder)
jakarta.faces.component.UIInput.REQUIRED = Diese Eingabe ist erforderlich.


# Double-Validierung (latitude, longitude)
jakarta.faces.converter.DoubleConverter.DOUBLE = Bitte geben Sie eine gültige Zahl für Koordinaten ein.


# Integer-Validierung (size)
jakarta.faces.converter.IntegerConverter.INTEGER = Bitte geben Sie eine gültige Ganzzahl ein.
